(devops) [ADD] push clang format modification

diff --git a/.github/workflows/github.yml b/.github/workflows/github.yml
--- a/.github/workflows/github.yml
+++ b/.github/workflows/github.yml
@@ -11,13 +11,25 @@ jobs:
       - name: Install clang-format
         run: |
           sudo apt-get install clang-format
-      - name: Check formatting
+      - name: Run format
+        run: find ./src \( -name '*.cpp' -or -name '*.hpp' -or -name '*.h' \) -not -path "./src/json.hpp" -exec clang-format -style=file {} \;
+      - name: Check if formated
         run: |
-          find ./src \( -name '*.cpp' -or -name '*.hpp' -or -name '*.h' \) -not -path "./src/json.hpp" -exec clang-format -style=file {} \;
           git diff --exit-code
+          status=$?
+          if [ $status -eq 0 ]; then
+            echo "clang-format check passed"
+          else
+            echo "clang-format check failed"
+            git add .
+            git commit -m "(clang-format) [FIX] format code by clang-format"
+            git push
+          fi
+
 
   linux:
     runs-on: ubuntu-latest
+    name: Check compilation for linux
     needs: [clang_format]
     steps:
       - uses: actions/checkout@v4
@@ -56,6 +68,7 @@ jobs:
 
   windows:
     runs-on: windows-latest
+    name: Check compilation for windows
     needs: [clang_format]
     steps:
       - uses: actions/checkout@v2
@@ -77,7 +90,7 @@ jobs:
   build:
     name: Create Release
     runs-on: ubuntu-latest
-    needs: [clang_format]
+    needs: [windows, linux]
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
@@ -139,8 +152,9 @@ jobs:
           asset_content_type: application/zip
 
   deploy_doxygen:
+    name: Generate doxygen documentation
     runs-on: ubuntu-latest
-    needs: [clang_format]
+    needs: [windows, linux]
     steps:
       - uses: actions/checkout@v2
       - name: Install dependencies
